### ISSUE TITLE
Photos

### ISSUE THREAD

**Issue by Zaturrby** [cth2015/cth-documentation#8]
It would be nice to have some photo's, they really define the look of the site. Mocking those will affect the look of the site beyond recognition. Don't we have a big stash of them somewhere?

**Comment by ghost** [comment]
I'd prefer to keep the site image- and contentless for now, so we can focus
on structure before moving on to discussions about color/images/wording
etc.

**Comment by Zaturrby** [comment]
Oké, keeping it really barebone for now then.
